### ISSUE TITLE
If new tab be closed, "parent" tab should be active

### ISSUE THREAD

**Issue by hao365** [ArnaudLigny/Open-New-Tab-After-Current-Tab#2]
There are two tabs: `tab 1` and `tab 2`.

1. Select `tab 1` as active
2. Press `Ctrl`+`T` to open `tab 3`
3. Type any URL in address bar and `Enter`
4. Press `Ctrl`+`W` to close `tab 3`

- Result: `tab 2` is active
- Expected: `tab 1` active because I created new tab from `tab 1`

**Comment by smac89** [comment]
This is nice, but it seems that chrome does not make any attempts to retain parent tab information. I attempted to tackle this, and only succeeded to an extent. Here is the log output:

```
background.js:48 Active tab: 406, opened by tab: undefined
background.js:48 Active tab: 461, opened by tab: 406
background.js:68 Moved new tab: 461 next to 406
background.js:48 Active tab: 462, opened by tab: 461
background.js:68 Moved new tab: 462 next to 461
background.js:48 Active tab: 461, opened by tab: undefined
background.js:48 Active tab: 463, opened by tab: 461
background.js:68 Moved new tab: 463 next to 461
background.js:48 Active tab: 462, opened by tab: undefined
background.js:90 Closed tab: 463
background.js:100 Active tab (463) closed, activating parent (461)
background.js:48 Active tab: 461, opened by tab: undefined
```

From the top:
We have existing tab (406)
Make another tab active (461 with parent 406)
Make another tab active (462 with parent 461)
Navigate back to 461 (now parent info is gone)
Make new tab open (463 with parent 461)
Close active tab (463)
Parent tab (461) is now opened (still missing parent info)

**Comment by SlowBubble** [comment]
Please take a look at my change: since children tabs are opened to the right, moving to the left on tab close will return to the "parent" tab.

**Comment by Spown** [comment]
[Tabsplus](https://chrome.google.com/webstore/detail/tabsplus/nikomkkhhpfoeamojhhgpfkpkdlfhfii) apparently can do this, so you could... "borrow" their code...
![](https://lh3.googleusercontent.com/_JMneSytPvU3Tx7WdNcUb7FYFfatdf23o8cmcw7j8L9uF47L7W4PlYjYbUVYorA1j0fUWFWLQPOgWiTCLCSVtFmU=w640-h400-e365-rj-sc0x00ffffff)
