### ISSUE TITLE
Open related tab at end of tab list

### ISSUE THREAD

**Issue by andrixnet** [ArnaudLigny/Open-New-Tab-After-Current-Tab#36]
While I understand this extension was born from a specific need useful for some, lot-of-confusing and counter-productive for others, I hereby make a feature request that would make it a more general purpose extension: 

Chrome, by default, opens a new empty tab at the end of the tab bar. (using Ctrl-T or + button). This extension changes that behaviour to the opposite - open the new tab next to the current one. 

The feature request is either for this becoming a general purpose extension regarding how new tabs are opened (configurable), or a dedicated separate extension.
Chrome, when right-click -> open_new_tab is requested, opens a new tab, by default, next to the current tab. For some people this is counter-productive and would desire the new tab to be opened at the end of the tab list. 

Thank you.

**Comment by ArnaudLigny** [comment]
Hello, I understand your request but this is not the goal of this extension: it handle the "new tab" event an try to create the new new after the active one.
There is a lot of others extensions that handles tabs and maybe answers your request.
