### ISSUE TITLE
It broke full of my tab groups

### ISSUE THREAD

**Issue by vuongtuha** [ArnaudLigny/Open-New-Tab-After-Current-Tab#42]
If you are using any tab group, your new tab opening will hold a slot in tab list. Then it kicked all after tab to the next tab. That make all of my tab groups after the new tab broken. 
I don't think many ppl running with 80 tab openings like me. But hope u can fix this issue

**Comment by ArnaudLigny** [comment]
Hello @vuongtuha, it should be fixed on Chrome and Edge with the last release ([0.4.6](https://github.com/ArnaudLigny/Open-New-Tab-After-Current-Tab/releases/tag/0.4.6)).
